//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public int IdLivro { get; set; }
        public System.DateTime DataReserva { get; set; }
        public Nullable<System.DateTime> DataEntrega { get; set; }
    
        public virtual Livro Livro { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
